on: push

jobs:
  release-project:
    name: Release compiled project to GitHub Releases
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download project content
      - uses: actions/download-artifact@v2
        with:
          name: main-exe
      - name: Archive project content
        uses: thedoctor0/zip-release@master
        with:
          filename: main-exe.zip
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}
      - name: Upload asset to Github Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./main-exe.zip
          asset_name: ProdigyMultiTool-v${{ github.run_number }}.zip
          asset_content_type: application/zip

  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - uses: actions/upload-artifact@v2
        with:
          name: main-exe
          path: src/dist/windows
